// Collects every user-facing English string of the QR catalogue and design presets into
// src/content/catalog-phrases.ts. Each translated language maps these phrases in its
// `phrases` dictionary; a test fails if any phrase is missing.
//
//   node --import tsx scripts/extract-phrases.ts     (re-run after editing the catalogue)
import fs from 'node:fs';
import path from 'node:path';
import { QR_TYPES, type FieldDef } from '../src/lib/qr/catalog';
import { BODY_SHAPES, COLOR_PRESETS, EYE_BALL_SHAPES, EYE_FRAME_SHAPES, FRAME_PRESETS, LOGO_PRESETS } from '../src/lib/qr/presets';

const phrases = new Set<string>();
const add = (value: unknown) => {
  if (typeof value === 'string' && value.trim() && /[A-Za-z]/.test(value)) phrases.add(value);
};

function walk(fields: FieldDef[] | undefined) {
  for (const field of fields ?? []) {
    add(field.label);
    add(field.placeholder);
    add(field.help);
    add(field.group);
    for (const option of field.options ?? []) add(option.label);
    walk(field.itemFields);
  }
}

for (const type of QR_TYPES) {
  add(type.label);
  add(type.tagline);
  add(type.description);
  add(type.category);
  walk(type.fields);
}
for (const list of [BODY_SHAPES, EYE_FRAME_SHAPES, EYE_BALL_SHAPES, FRAME_PRESETS, LOGO_PRESETS, COLOR_PRESETS] as { label: string; group?: string }[][]) {
  for (const entry of list) {
    add(entry.label);
    add(entry.group);
  }
}

const sorted = [...phrases].sort((a, b) => a.localeCompare(b));
const out = `// Generated by scripts/extract-phrases.ts. Do not edit by hand.
// Every English string of the QR catalogue and design presets that a visitor can see.
export const CATALOG_PHRASES: readonly string[] = ${JSON.stringify(sorted, null, 2)};
`;
fs.writeFileSync(path.resolve(import.meta.dirname, '../src/content/catalog-phrases.ts'), out);
console.log(`${sorted.length} phrases -> src/content/catalog-phrases.ts`);
